---
abstract: 'Async client to talk to beanstalkd server'
author:
  - 'Graham Barr'
generated_by: 'Dist::Zilla version 1.100521'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Beanstalk
requires:
  AnyEvent: 0
  Class::Accessor::Fast: 0
  ExtUtils::MakeMaker: 6.11
  YAML: 0
resources:
  homepage: http://search.cpan.org/dist/AnyEvent-Beanstalk/
  repository: http://github.com/gbarr/AnyEvent-Beanstalk
version: 1.100790
